### ISSUE TITLE
mkdocstring' setup_commands isn't supported by the new Python handler

### ISSUE THREAD

**Issue by pawamoy** [fpgmaas/cookiecutter-uv#6]
**Describe the bug**

I was taking a quick glance at your repository (nice cookiecutter!) and noticed you're using `setup_commands` in the configuration of mkdocstrings in mkdocs.yml. This option isn't supported by the new Python handler (which isn't really new anymore).

Instead of using `setup_commands` to insert the right paths into `sys.path`, you should use the [`paths` option](https://mkdocstrings.github.io/python/usage/#paths), which is much more robust :smile:

**Comment by fpgmaas** [comment]
Thanks for raising this! (and thanks for developing `mkdocstrings`). I resolved this in https://github.com/fpgmaas/cookiecutter-uv/pull/7
