### ISSUE TITLE
docs:  Config for deptry incorrect

### ISSUE THREAD

**Issue by jmgate** [fpgmaas/cookiecutter-uv#9]
In https://github.com/fpgmaas/cookiecutter-uv/blob/main/docs/features/linting.md, the configuration listed under **deptry** is just a copy/paste of the configuration for **mypy** above.

**Comment by fpgmaas** [comment]
Oops, thanks for raising this! Will update the page :)

**Comment by fpgmaas** [comment]
Solved by #10
